#!/usr/bin/php
<?php

require_once(dirname(__FILE__) . '/arguments');

$args = getArguments($argc, $argv);
echo '<?xml version="1.0" encoding="UTF-8"?>';

function atomDate($date) {
	$value = date('Y-m-d\TH:i:s', $date);
	if (date('P', $date) == "P") {
		/* Crap. Looks like this version doesn't have P, like the one I have locally */
		/* It's emulation time! */
		$tz = date('Z', $date) / 60;
		$m = $tz % 60;
		$h = ($tz - $m) / 60;
		$value = $value . sprintf('%+03d:%02d', $h, $m);
	} else {
		$value = $value . date('P', $date);
	}

	return $value;
}
?>

<feed xmlns="http://www.w3.org/2005/Atom">

	<title>psycoti.ca/0/ - Articles</title>
	<link href="http://psycoti.ca/0/feed.atom" rel="self" />
	<link href="http://psycoti.ca/0/" />
	<id>http://psycoti.ca/0/feed.atom</id>
	<updated><?php print(atomDate(time())) ?></updated>
	<author>
		<name>Christopher Vollick</name>
		<email>psycotica0@gmail.com</email>
	</author>
	<generator uri="http://git.psycoti.ca/%3fa=summary%26p=GitSite">GitSite</generator>
	<icon>http://psycoti.ca/0/static/avatar.png</icon>
	<?php print($args['Content']) ?>
</feed>
