#!/usr/bin/php
<?php

require_once(dirname(__FILE__) . '/arguments');

$args = getArguments($argc, $argv);

function atomDate($date) {
	$value = date('Y-m-d\TH:i:s', $date);
	if (date('P', $date) == "P") {
		/* Crap. Looks like this version doesn't have P, like the one I have locally */
		/* It's emulation time! */
		$tz = date('Z', $date) / 60;
		$m = $tz % 60;
		$h = ($tz - $m) / 60;
		$value = $value . sprintf('%+03d:%02d', $h, $m);
	} else {
		$value = $value . date('P', $date);
	}

	return $value;
}

?>
<entry>
	<title><?php print($args['Title']) ?></title>
	<?php 
		print('<link rel="alternate" type="text/html" href="http://psycoti.ca/0/articles/' . $args['Self'] . '"/>');
	?>
	<?php 
		print('<id>http://psycoti.ca/0/id/' . $args['ID'] . '</id>');
	?>
	<updated><?php print(atomDate($args['ModificationDate'])) ?></updated>
	<published><?php print(atomDate($args['CreationDate'])) ?></published>
	<content type="html">
		<![CDATA[
			<?php print(htmlentities($args['Content'])) ?>
		]]>
	</content>
</entry>
