#!/usr/bin/php
<?php

require_once(dirname(__FILE__) . '/arguments');

$args = getArguments($argc, $argv);
?>
<div id="bio" class="vcard">
<img class='photo' src='http://psycoti.ca/0/static/avatar.png' alt='My Avatar' />
<span class="fn"> Christopher Vollick </span>
<span class="nickname"> psycotica0 </span>
<span class="email"> &lt;psycotica0@gmail.com&gt; </span>
</div>

<p id="greeting"> Hello. This is the personal website of Christopher Vollick </p>
<p> The navigational menu should be used to navigate to whatever it is you're interested in </p>
<p> Below are the last couple articles I've written. </p>
<p> Thanks for visiting </p>

<div id="recent">
<?php print($args['Content']) ?>
</div>
