#!/usr/bin/php
<?php

require_once(dirname(__FILE__) . '/arguments');

$args = getArguments($argc, $argv);
?>
<h1> <?php echo "<a href='" . $args['Root'] . "articles/" . $args['Self'] . "'> " . $args['Title'] . " </a>"; ?></h1>
<?php echo $args['Content']; ?>
