#!/usr/bin/php
<?php

require_once(dirname(__FILE__) . '/arguments');

$args = getArguments($argc, $argv);

echo '<?xml version="1.0" encoding="UTF-8"?>';
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<title> <?php echo $args['Title']; ?> - psycoti.ca/0/</title>

<?php
echo "<link rel='stylesheet' href='" . $args['Root'] . "static/style.css' />\n";
echo "<link rel='openid.server' href='http://id.psycoti.ca/' />\n";
echo "<link rel='openid.delegate' href='http://id.psycoti.ca/' />\n";
echo "<link rel='alternate' type='application/atom+xml' href='" . $args['Root'] . "feed.atom' />\n";
if (!empty($args['NextLink'])) {
	echo "<link rel='next' href='" . $args['Root'] . "articles/" . $args['NextLink'] . "' />\n";
}
if (!empty($args['PreviousLink'])) {
	echo "<link rel='prev' href='" . $args['Root'] . "articles/" . $args['PreviousLink'] . "' />\n";
}
if (!empty($args['Self'])) {
	echo "<link rel='self' href='" . $args['Root'] . "articles/" . $args['Self'] . "' />\n";
}
if (!empty($args['ID'])) {
	echo "<link rel='canonical' href='" . $args['Root'] . "id/" . $args['ID'] . "' />\n";
}
?>
</head>
<body>

<div id="header">
<h1> psycoti.ca/0/ </h1>
</div>

<div id="menu">
<ul>
<li> <a href="http://github.com/psycotica0"> Code </a> </li>
<li> <a> Projects </a> </li>
<li> <a> Ideas </a> </li>
<li> <a> Stuff </a> </li>
</ul>
</div>

<div id="content">
<?php echo $args['Content']; ?>
</div>

</body>
</html>
